import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { DM_Sans } from "next/font/google";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import Navbar from "@/components/navbar";
import { Toaster } from "sonner";
import { Icon } from "@iconify/react";

export const metadata: Metadata = {
   title: "NTRWL",
   description: "Generated by create next app",
};

const dmSans = DM_Sans({
   variable: "--font-dm-sans",
   subsets: ["latin"]
});

const againts = localFont({
   src: "./fonts/againts.otf",
   fallback: ["Inter"],
   variable: "--font-againts",
});

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className="scroll-smooth scroll-pt-16">
         <body
            className={`${dmSans.variable}  ${againts.variable} antialiased`}
         >
            <NuqsAdapter>
               <Navbar />
               <main className="w-[min(1200px,90%)] mx-auto py-16">
                  {children}
               </main>
               <Toaster
                  position="top-center"
                  className="font-dmSans"
                  duration={5000}
                  icons={{
                     success: (
                        <Icon
                           icon="solar:check-circle-outline"
                           className="size-4"
                           strokeWidth={2}
                        />
                     ),
                     error: (
                        <Icon
                           icon="solar:close-circle-outline"
                           className="size-4"
                           strokeWidth={2}
                        />
                     ),
                  }}
                  closeButton
               />
            </NuqsAdapter>
         </body>
      </html>
   );
}
